force-app/main/default/objects/Asset_Request__c/Asset_Request__c.object-meta.xml
<CustomObject>
    <label>Asset Request</label>
    <nameField>
        <displayFormat>Req-{00000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asset Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Allocated</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EmployeeDashboardController.cls
public with sharing class EmployeeDashboardController {
   @AuraEnabled(cacheable=true)
    public static EmployeeDashboardWrapper getEmployeeDashboard() {

        EmployeeDashboardWrapper wrapper = new EmployeeDashboardWrapper();

        List<Asset_Request__c> requests = EmployeeDashboardSelector.getAllRequests();

        wrapper.requests = requests;
        wrapper.totalRequests = requests.size();

        for (Asset_Request__c request : requests) {

            if (request.Status__c == AssetConstants.REQUEST_STATUS_PENDING) {
                wrapper.pendingRequests++;
            }
            else if (request.Status__c == AssetConstants.REQUEST_STATUS_APPROVED) {
                wrapper.approvedRequests++;
            }
            else if (request.Status__c == AssetConstants.REQUEST_STATUS_REJECTED) {
                wrapper.rejectedRequests++;
            }
        }

        return wrapper;
    }
}