force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <label>Asset</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Allocated</fullName>
            </value>
            <value>
                <fullName>Repair</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Retired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset_History__c/Asset_History__c.object-meta.xml
<CustomObject>
    <label>Asset History</label>
    <nameField>
        <label>Asset History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Historeis</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset_History__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <label>Asset</label>
    <referenceTo>Asset__c</referenceTo>
    <relationshipLabel>Asset Histories</relationshipLabel>
    <relationshipName>Asset_Histories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Asset_History__c/fields/Asset_Request__c.field-meta.xml
<CustomField>
    <fullName>Asset_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset Request</label>
    <referenceTo>Asset_Request__c</referenceTo>
    <relationshipLabel>Asset Historeis</relationshipLabel>
    <relationshipName>Asset_Historeis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset_History__c/fields/Changed_By__c.field-meta.xml
<CustomField>
    <fullName>Changed_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Changed By</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Asset History Changes</relationshipLabel>
    <relationshipName>Asset_History_Changes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset_History__c/fields/Changed_On__c.field-meta.xml
<CustomField>
    <fullName>Changed_On__c</fullName>
    <label>Changed On</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Asset_History__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Asset Historeis (Employee)</relationshipLabel>
    <relationshipName>Asset_Historeis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset_History__c/fields/Old_Status__c.field-meta.xml
<CustomField>
    <fullName>Old_Status__c</fullName>
    <label>Old Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset_Request__c/Asset_Request__c.object-meta.xml
<CustomObject>
    <label>Asset Request</label>
    <nameField>
        <displayFormat>Req-{00000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asset Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset_Request__c/fields/Approval_Remarks__c.field-meta.xml
<CustomField>
    <fullName>Approval_Remarks__c</fullName>
    <label>Approval Remarks</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Asset_Request__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset__c</referenceTo>
    <relationshipLabel>Asset Requests</relationshipLabel>
    <relationshipName>Asset_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset_Request__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Asset Requests</relationshipLabel>
    <relationshipName>Asset_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Allocated</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Resigned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AssetAllocationService.cls
public with sharing class AssetAllocationService {
    public static void allocateAssets(List<Asset_Request__c> newList, Map<Id, Asset_Request__c> oldMap){
        List<Asset__c> assetToUpdate = new List<Asset__c>();
        List<Asset_History__c> assetHistoryToInsert = new List<Asset_History__c>();
        Set<Id> assetIds = new Set<Id>();

        for(Asset_Request__c request : newList){
            if(request.Asset__c != null){
                assetIds.add(request.Asset__c);
            }
        }

        Map<Id, Asset__c> assetMap = new Map<Id, Asset__c>([SELECT Id, Status__c FROM Asset__c WHERE Id IN :assetIds]);

        for(Asset_Request__c request : newList){
            Asset_Request__c oldRequest = oldMap.get(request.Id);
            
            if( request.Asset__c != null && 
                oldRequest.Status__c == AssetConstants.REQUEST_STATUS_PENDING && 
                request.Status__c == AssetConstants.REQUEST_STATUS_APPROVED){
                
                Asset__c asset = new Asset__c(
                    Id = request.Asset__c,
                    Status__c = AssetConstants.ASSET_STATUS_ALLOCATED
                );
                assetToUpdate.add(asset);

                Asset_History__c assetHistory = new Asset_History__c(
                    Asset__c = request.Asset__c,
                    Employee__c = request.Employee__c,
                    Asset_Request__c = request.Id,
                    Changed_On__c = System.now(),
                    Changed_By__c = UserInfo.getUserId(),
                    Old_Status__c = assetMap.get(request.Asset__c).Status__c,
                    New_Status__c = AssetConstants.ASSET_STATUS_ALLOCATED,
                    Remarks__c = request.Approval_Remarks__c 
                );
                assetHistoryToInsert.add(assetHistory);
            }
        }
    
        if(!assetToUpdate.isEmpty()){
            update assetToUpdate;
        }
        if(!assetHistoryToInsert.isEmpty()){
            insert assetHistoryToInsert;
        }
    }
}