force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <label>Asset</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset_Request__c/Asset_Request__c.object-meta.xml
<CustomObject>
    <label>Asset Request</label>
    <nameField>
        <displayFormat>Req-{00000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asset Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset_Request__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset__c</referenceTo>
    <relationshipLabel>Asset Requests</relationshipLabel>
    <relationshipName>Asset_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset_Request__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Asset Requests</relationshipLabel>
    <relationshipName>Asset_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AssetController.cls
public with sharing class AssetController {
    public AssetController() {

    }

    @AuraEnabled
    public static String requestAsset(Map<String, Object> assetRequest) {
        Id employeeId = (Id) assetRequest.get('employeeId');
        Id assetId = (Id) assetRequest.get('assetId');
        String priority = (String) assetRequest.get('priority');
        String reason = (String) assetRequest.get('reason');

        AssetRequestWrapper wrapper = new AssetRequestWrapper(employeeId, assetId, priority, reason);
        return AssetService.requestAsset(wrapper);
    }

    @AuraEnabled(cacheable=true)
    public static List<Employee__c> getActiveEmployees(){
        return AssetService.getActiveEmployees();
    }

    @AuraEnabled(cacheable=true)
    public static List<Asset__c> getAvailableAssets(){
        return AssetService.getAvailableAssets();
    }

    @AuraEnabled(cacheable=true)
    public static List<Asset_Request__c> getPendingRequests(){
        return AssetService.getPendingRequests();
    }

    @AuraEnabled
    public static void updateRequestStatus(Id requestId, String status){
        AssetService.updateRequestStatus(requestId , status);
    }
}