force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <label>Asset</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Allocated</fullName>
            </value>
            <value>
                <fullName>Repair</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Retired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset_Request__c/Asset_Request__c.object-meta.xml
<CustomObject>
    <label>Asset Request</label>
    <nameField>
        <displayFormat>Req-{00000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asset Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset_Request__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset__c</referenceTo>
    <relationshipLabel>Asset Requests</relationshipLabel>
    <relationshipName>Asset_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset_Request__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Asset Requests</relationshipLabel>
    <relationshipName>Asset_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Allocated</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Resigned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public with sharing class TestDataFactory {
    public static Employee__c createEmployee(){
        Employee__c employee = new Employee__c(
            Name = 'Test Employee',
            Status__c = AssetConstants.EMPLOYEE_STATUS_ACTIVE,
            Manager__c = createManager().Id);
        insert employee;
        return employee;
    }

    public static Employee__c createEmployee(Id managerId){
        Employee__c employee = new Employee__c(
            Name = 'Test Employee',
            Status__c = AssetConstants.EMPLOYEE_STATUS_ACTIVE,
            Manager__c = managerId);
        insert employee;
        return employee;       
    }

    public static Employee__c createEmployee(String status , Id managerId){
        Employee__c employee = new Employee__c(
            Name = 'Test Employee',
            Status__c = status,
            Manager__c = managerId
        );
        insert employee;
        return employee;
    }

    public static Employee__c createManager(){
        Employee__c manager = new Employee__c(
            Name = 'Test Manager',
            Status__c = AssetConstants.EMPLOYEE_STATUS_ACTIVE
        );
        insert manager;
        return manager;
    }

    public static Asset__c createAsset(){
        Asset__c asset = new Asset__c(
            Name = 'Test Asset',
            Status__c = AssetConstants.ASSET_STATUS_AVAILABLE
        );
        insert asset;
        return asset;
    }

    public static Asset_Request__c createAssetRequest(Id employeeId, Id assetId){
        Asset_Request__c assetRequest = new Asset_Request__c(
            Employee__c = employeeId,
            Asset__c = assetId,
            Status__c = AssetConstants.REQUEST_STATUS_PENDING
        );
        insert assetRequest;
        return assetRequest;
    }
}